drop table car if exists;
create table car (
  id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  make varchar(25) not null,
  model varchar(50) not null,
  price integer not null
);